<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Tugas_QAC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>73728aaf-3178-4f41-8188-e4328daa5627</testSuiteGuid>
   <testCaseLink>
      <guid>6f8092fa-7373-41d4-ad76-35fc3c11ce5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tugas QAC/BookApointment</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a8c67d82-0bd7-4c7c-ab5a-4da9f6f60e4a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Tugas QAC/BookAppointment</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a8c67d82-0bd7-4c7c-ab5a-4da9f6f60e4a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>RadBut_xls</value>
         <variableId>62629e69-f0c6-41dc-a7c5-84c222b5f4da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a8c67d82-0bd7-4c7c-ab5a-4da9f6f60e4a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CekBox_xls</value>
         <variableId>15a1ce59-97a3-4d03-a187-a015a97a1bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a8c67d82-0bd7-4c7c-ab5a-4da9f6f60e4a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Note_xls</value>
         <variableId>a1cc2cc0-8605-4b2c-9e6d-6ef31b475dcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a8c67d82-0bd7-4c7c-ab5a-4da9f6f60e4a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DropDown_xls</value>
         <variableId>c7364acb-2d20-41a4-85ca-e98fc06d627a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a8c67d82-0bd7-4c7c-ab5a-4da9f6f60e4a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Date_xls</value>
         <variableId>ca0eacc5-2be4-4b09-b239-ae26ee470ae4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f525d3b5-ce72-458a-8642-2e74ead25bcd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Tugas QAC/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c0af5c63-3e6c-4706-af7a-cbec39ff6fa4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Tugas QAC/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c0af5c63-3e6c-4706-af7a-cbec39ff6fa4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username_xls</value>
         <variableId>670ba988-7ffd-43a2-82b3-3c8003d5c4eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c0af5c63-3e6c-4706-af7a-cbec39ff6fa4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password_xls</value>
         <variableId>a05cc5f2-919a-4411-9a76-2688f26e354e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58361a58-c48f-48c3-acd3-e966920faae7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Tugas QAC/Cek Status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ec31040-cf34-4065-b443-41b44f658d42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09d8f655-720d-4bab-81b1-34cec85aef4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5203b039-9ea8-4acc-ab9a-3d6c19196291</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Tugas QAC/Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5617ba4-6077-45e1-af54-e6437e72371d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>662c50b4-1ba7-46c6-9369-c024c2cb2de1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
