<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_makanan_icon-bag2</name>
   <tag></tag>
   <elementGuidId>293e0786-1f25-4626-b4cc-bb3a11381593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.header__extra > i.icon-bag2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-bag2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/header[@class=&quot;header header--1&quot;]/div[@class=&quot;header__top&quot;]/div[@class=&quot;ps-container&quot;]/div[@class=&quot;header__right&quot;]/div[@class=&quot;header__actions&quot;]/div[@class=&quot;ps-cart--mini&quot;]/a[@class=&quot;header__extra&quot;]/i[@class=&quot;icon-bag2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/i</value>
   </webElementXpaths>
</WebElementEntity>
